### ISSUE TITLE
Get rid of border on iPhone button

### ISSUE THREAD

**Issue by jahoni** [phonegap/app.phonegap.com#15]

**Comment by timkim** [comment]
Fixed in a few commits: 
https://github.com/nitobi/app.phonegap.com/commit/90b70678554013377e029b37cf4868504cc75bce

https://github.com/nitobi/app.phonegap.com/commit/d4a41b214408e231b97410d6a9bf52af6e646475

https://github.com/nitobi/app.phonegap.com/commit/87db09250a3fc797d8ab4874494572c984df87c7
