### ISSUE TITLE
Less Vibrant the Colors

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/app.phonegap.com#6]
**Currently**

I like the colors, but they are too strong.

![alternate](https://f.cloud.github.com/assets/21328/2424301/695e361c-aba5-11e3-81ed-9f6ed8bdd571.png)

**Suggestion**

Reduce the vibrance and balance the saturation. I dunno... I'm no designer but here's a crude Photoshop edit.

![colors](https://f.cloud.github.com/assets/21328/2424318/f128b05e-aba5-11e3-82d2-991f865d646a.png)

**Comment by jahoni** [comment]
updated to have variable blue background for steps, save the the POWER section.
