### ISSUE TITLE
Emphasize the Sections as Steps

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/app.phonegap.com#7]
**Problem**

Early on, we decided that the site should explain the new developer workflow. Instead of having fluffy features in each section, we wanted to explains the steps to the new workflow.

At the moment, we have the content there but the feel of a walkthrough is missing.

**Suggestion**

Somehow show that each section leads to the next.

Maybe arrows?

![arrows](https://f.cloud.github.com/assets/21328/2424352/6f888e7e-aba6-11e3-94da-f8d8a34351cd.png)

Or maybe something more obvious, such as numbers circled with arrows looping down to the next section?

![steps](https://f.cloud.github.com/assets/21328/2424442/9c737c18-aba7-11e3-8b35-fadf447e040f.png)

Ugly, I know. I'm just trying to illustrate the idea.

**Comment by jahoni** [comment]
We're going to go with the notched arrow, and add more description to the section header. That is:

First, install the PhoneGap CLI

Next, get the mobile app

Now, pair the CLI to the mobile app

**Comment by jahoni** [comment]
added arrows and updated section headers
