### ISSUE TITLE
Dark Header instead of Light Header?

### ISSUE THREAD

**Issue by mwbrooks** [phonegap/app.phonegap.com#8]
**Current**

![arrows](https://f.cloud.github.com/assets/21328/2424480/16b7bdcc-aba8-11e3-9067-48b05ebcb489.png)

**Suggestion**

![header](https://f.cloud.github.com/assets/21328/2424482/1d0f0b58-aba8-11e3-9632-be71bbdd7b68.png)

**Comment by jahoni** [comment]
I want the header for subdomains to remain consistent, and also to reference styling back to the parent (phonegap.com). The goal here is to prevent any confusion amongst users by appearing the "same" as the parent, but without the same global navigation ("uhhh...where am i?"). The styling before was correct (with the light texture background that is used on phonegap.com). To mitigate this, and to differentiate the hero area from the "instructions" and to contrast the header, I recommend changing the hero background colour to #2d3033. 

Making a colour change to the background of the hero may require editing the hero SVG for better contrast.

**Comment by jahoni** [comment]
updated, as above.
